### PR TITLE
Docker overhaul

### PR DESCRIPTION
**Pull request by FoxNerdSaysMoo**
Added `.env` file which is used to configure the build.

### CODE REVIEW

**Comment by FoxNerdSaysMoo** [comment]
I've tested the default config (the one I committed), and where the config uses ssl and runs on a different port (`SSL=ssl CERT_NAME=... PORT=668`)

**Comment by FoxNerdSaysMoo** [comment]
Resolved conflicts

**Comment by FoxNerdSaysMoo** [comment]
This fixes #95 (no idea why, but it does)

**Comment by FoxNerdSaysMoo** [comment]
If you merge please **`Squash and merge`**

**Comment by binary-person** [comment]
having an .env file seems like a nice idea. however, that will make it confusing with the already existing docker-compose.yml file

adding ssl will make things more complicated than it needs to be (you also need to consider renewal of certificates. you can mount the letsencrypt host folder but like i said, makes things more complicated). the docker version was meant to ease up on the host's nginx configuration, so the ssl was meant to be done by the host's reverse proxy.

thank you for your efforts on the the pull request, but i won't be merging it into the main repo for the reasons stated above

**Pull request closed without merging**
